name: testing

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  test:
    services:
      local_mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"

      - name: Install dependencies
        run: |
          pip install uv
          LLVM_CONFIG=/home/runner/work/atomate2/atomate2/llvm-config uv pip install .[strict,tests,abinit] --system --prerelease=allow
          # latest ase needed to get FrechetCellFilter used by ML force fields
          # TODO remove next line installing ase from main branch when FrechetCellFilter is released
          uv pip install --upgrade 'git+https://gitlab.com/ase/ase' --system
          uv pip install torch-runstats --system
          uv pip install --no-deps nequip --system

          # Install pseudos for abinit tests
          mkdir -p ~/.abinit/pseudos
          cp -r tests/test_data/abinit/pseudos/ONCVPSP-PBE-SR-PDv0.4 ~/.abinit/pseudos

      - name: Test
        env:
          MP_API_KEY: ${{ secrets.MP_API_KEY }}
        run: pytest --cov=atomate2 --cov-report=xml

      - uses: codecov/codecov-action@v1
        if: matrix.python-version == '3.10' && github.repository == 'materialsproject/atomate2'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install .[strict,docs] --system
          # ase needed to get FrechetCellFilter used by ML force fields
          uv pip install --upgrade 'git+https://gitlab.com/ase/ase' --system

      - name: Build
        run: sphinx-build docs docs_build

  automerge:
    needs: [lint, test, docs]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
